#!/usr/bin/env node
/**
 * Fetches S&P 500 constituents (GICS sectors) and financials, merges by Symbol,
 * and writes src/data/sp500Constituents.ts with correct sectors and financial stats.
 * Run: node scripts/fetch-sp500.mjs
 */

import { writeFileSync } from 'fs';

function parseCSVLine(line) {
  const out = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (c === '"') {
      inQuotes = !inQuotes;
    } else if ((c === ',' && !inQuotes) || c === '\r') {
      out.push(cur.trim());
      cur = '';
    } else {
      cur += c;
    }
  }
  out.push(cur.trim());
  return out;
}

async function fetchText(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Fetch failed: ${res.status} ${url}`);
  return res.text();
}

async function main() {
  const [constituentsText, financialsText] = await Promise.all([
    fetchText('https://raw.githubusercontent.com/datasets/s-and-p-500-companies/master/data/constituents.csv'),
    fetchText('https://raw.githubusercontent.com/datasets/s-and-p-500-companies-financials/master/data/constituents-financials.csv')
  ]);

  const constituentLines = constituentsText.split('\n').filter(Boolean);
  const financialLines = financialsText.split('\n').filter(Boolean);
  const headerConst = constituentLines[0];
  const headerFin = financialLines[0];

  const constituents = new Map(); // Symbol -> { name, sector }
  for (let i = 1; i < constituentLines.length; i++) {
    const row = parseCSVLine(constituentLines[i]);
    const symbol = row[0];
    const security = row[1] || symbol;
    const gicsSector = row[2] || 'Unknown';
    constituents.set(symbol, { name: security, sector: gicsSector });
  }

  const financials = new Map(); // Symbol -> { pe, divYield, marketCap }
  for (let i = 1; i < financialLines.length; i++) {
    const row = parseCSVLine(financialLines[i]);
    const symbol = row[0];
    const peRaw = row[4];
    const divYieldRaw = row[5];
    const marketCapRaw = row[9];
    const pe = peRaw && !isNaN(parseFloat(peRaw)) ? Math.round(parseFloat(peRaw) * 10) / 10 : 0;
    const divYieldDecimal = divYieldRaw && !isNaN(parseFloat(divYieldRaw)) ? parseFloat(divYieldRaw) : 0;
    const divYield = Math.round(divYieldDecimal * 1000) / 10; // e.g. 0.0199 -> 1.99
    const marketCapDollars = marketCapRaw && !isNaN(parseFloat(marketCapRaw)) ? parseFloat(marketCapRaw) : 0;
    const marketCap = Math.round(marketCapDollars / 1e6); // store in millions
    financials.set(symbol, { pe, divYield, marketCap });
  }

  const stocks = [];
  for (const [symbol, { name, sector }] of constituents) {
    const fin = financials.get(symbol) || { pe: 0, divYield: 0, marketCap: 0 };
    stocks.push({
      ticker: symbol,
      name,
      marketCap: fin.marketCap || 0,
      pe: fin.pe || 0,
      divYield: fin.divYield || 0,
      sector,
      index: 'SP500'
    });
  }

  const tsContent = `/**
 * S&P 500 constituents with GICS sectors and financial data.
 * Generated by scripts/fetch-sp500.mjs from:
 *   - constituents.csv (GICS Sector)
 *   - constituents-financials.csv (P/E, Dividend Yield, Market Cap)
 * marketCap in millions, divYield in %.
 */

import { Stock } from '../types/colt-road';

export const SP500_STOCKS: Stock[] = ${JSON.stringify(stocks, null, 2).replace(/"([^"]+)":/g, '$1:')};
`;

  writeFileSync(new URL('../src/data/sp500Constituents.ts', import.meta.url), tsContent);
  console.log(`Wrote ${stocks.length} S&P 500 stocks to src/data/sp500Constituents.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
