/**
 * S&P 500 constituents with GICS sectors and financial data.
 * Generated by scripts/fetch-sp500.mjs from:
 *   - constituents.csv (GICS Sector)
 *   - constituents-financials.csv (P/E, Dividend Yield, Market Cap)
 * marketCap in millions, divYield in %.
 */

import { Stock } from '../types/colt-road';

export const SP500_STOCKS: Stock[] = [
  {
    ticker: "MMM",
    name: "3M",
    marketCap: 83294,
    pe: 21.3,
    divYield: 2,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "AOS",
    name: "A. O. Smith",
    marketCap: 9758,
    pe: 18.5,
    divYield: 2,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "ABT",
    name: "Abbott Laboratories",
    marketCap: 221889,
    pe: 16.7,
    divYield: 2,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "ABBV",
    name: "AbbVie",
    marketCap: 324977,
    pe: 64.3,
    divYield: 3.7,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "ACN",
    name: "Accenture",
    marketCap: 240779,
    pe: 32.3,
    divYield: 1.7,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "ADBE",
    name: "Adobe Inc.",
    marketCap: 190422,
    pe: 35.4,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "AMD",
    name: "Advanced Micro Devices",
    marketCap: 192886,
    pe: 105.4,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "AES",
    name: "AES Corporation",
    marketCap: 7821,
    pe: 7.6,
    divYield: 6.2,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "AFL",
    name: "Aflac",
    marketCap: 59653,
    pe: 16,
    divYield: 2.1,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "A",
    name: "Agilent Technologies",
    marketCap: 43273,
    pe: 34.1,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "APD",
    name: "Air Products",
    marketCap: 74555,
    pe: 19.5,
    divYield: 2.1,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "ABNB",
    name: "Airbnb",
    marketCap: 81951,
    pe: 45.4,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "AKAM",
    name: "Akamai Technologies",
    marketCap: 15008,
    pe: 29.6,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "ALB",
    name: "Albemarle Corporation",
    marketCap: 9896,
    pe: 0,
    divYield: 1.9,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "ARE",
    name: "Alexandria Real Estate Equities",
    marketCap: 16851,
    pe: 54.1,
    divYield: 5.2,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "ALGN",
    name: "Align Technology",
    marketCap: 16357,
    pe: 37.4,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "ALLE",
    name: "Allegion",
    marketCap: 11538,
    pe: 20.4,
    divYield: 1.4,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "LNT",
    name: "Alliant Energy",
    marketCap: 15109,
    pe: 22.9,
    divYield: 3.4,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "ALL",
    name: "Allstate",
    marketCap: 50930,
    pe: 12.4,
    divYield: 1.9,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "GOOGL",
    name: "Alphabet Inc. (Class A)",
    marketCap: 2507304,
    pe: 27.1,
    divYield: 0.4,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "GOOG",
    name: "Alphabet Inc. (Class C)",
    marketCap: 2504763,
    pe: 27.3,
    divYield: 0.4,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "MO",
    name: "Altria",
    marketCap: 88303,
    pe: 7.9,
    divYield: 7.8,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "AMZN",
    name: "Amazon",
    marketCap: 2499205,
    pe: 50.2,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "AMCR",
    name: "Amcor",
    marketCap: 14092,
    pe: 18.3,
    divYield: 5.2,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "AEE",
    name: "Ameren",
    marketCap: 25145,
    pe: 22.2,
    divYield: 2.8,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "AEP",
    name: "American Electric Power",
    marketCap: 52383,
    pe: 19.8,
    divYield: 3.8,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "AXP",
    name: "American Express",
    marketCap: 223903,
    pe: 22.8,
    divYield: 0.9,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "AIG",
    name: "American International Group",
    marketCap: 45947,
    pe: 14.6,
    divYield: 2.1,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "AMT",
    name: "American Tower",
    marketCap: 86425,
    pe: 44.7,
    divYield: 3.5,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "AWK",
    name: "American Water Works",
    marketCap: 24292,
    pe: 24.7,
    divYield: 2.5,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "AMP",
    name: "Ameriprise Financial",
    marketCap: 52271,
    pe: 21.8,
    divYield: 1,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "AME",
    name: "Ametek",
    marketCap: 42690,
    pe: 32.1,
    divYield: 0.6,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "AMGN",
    name: "Amgen",
    marketCap: 153423,
    pe: 36.2,
    divYield: 3.4,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "APH",
    name: "Amphenol",
    marketCap: 85333,
    pe: 36.9,
    divYield: 0.9,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "ADI",
    name: "Analog Devices",
    marketCap: 105128,
    pe: 64.8,
    divYield: 1.7,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "AON",
    name: "Aon plc",
    marketCap: 80196,
    pe: 31.7,
    divYield: 0.7,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "APA",
    name: "APA Corporation",
    marketCap: 8113,
    pe: 3.1,
    divYield: 4.4,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "APO",
    name: "Apollo Global Management",
    marketCap: 0,
    pe: 0,
    divYield: 0,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "AAPL",
    name: "Apple Inc.",
    marketCap: 3572851,
    pe: 37.8,
    divYield: 0.4,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "AMAT",
    name: "Applied Materials",
    marketCap: 147684,
    pe: 21.1,
    divYield: 0.9,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "APTV",
    name: "Aptiv",
    marketCap: 14786,
    pe: 7,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "ACGL",
    name: "Arch Capital Group",
    marketCap: 35585,
    pe: 6.3,
    divYield: 0,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "ADM",
    name: "Archer Daniels Midland",
    marketCap: 24515,
    pe: 14.4,
    divYield: 3.8,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "ANET",
    name: "Arista Networks",
    marketCap: 145162,
    pe: 55.4,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "AJG",
    name: "Arthur J. Gallagher & Co.",
    marketCap: 75396,
    pe: 46.5,
    divYield: 0.9,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "AIZ",
    name: "Assurant",
    marketCap: 11037,
    pe: 15.4,
    divYield: 1.5,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "T",
    name: "AT&T",
    marketCap: 172368,
    pe: 16.1,
    divYield: 4.9,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "ATO",
    name: "Atmos Energy",
    marketCap: 22180,
    pe: 20.9,
    divYield: 2.4,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "ADSK",
    name: "Autodesk",
    marketCap: 67097,
    pe: 62,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "ADP",
    name: "Automatic Data Processing",
    marketCap: 123286,
    pe: 31.6,
    divYield: 2.1,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "AZO",
    name: "AutoZone",
    marketCap: 56224,
    pe: 22.4,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "AVB",
    name: "AvalonBay Communities",
    marketCap: 31507,
    pe: 30.3,
    divYield: 3.1,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "AVY",
    name: "Avery Dennison",
    marketCap: 14923,
    pe: 21.3,
    divYield: 1.8,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "AXON",
    name: "Axon Enterprise",
    marketCap: 49732,
    pe: 169,
    divYield: 0,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "BKR",
    name: "Baker Hughes",
    marketCap: 45696,
    pe: 15.5,
    divYield: 2.1,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "BALL",
    name: "Ball Corporation",
    marketCap: 16622,
    pe: 23.2,
    divYield: 1.4,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "BAC",
    name: "Bank of America",
    marketCap: 352383,
    pe: 14.4,
    divYield: 2.2,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "BAX",
    name: "Baxter International",
    marketCap: 16625,
    pe: 130.2,
    divYield: 2,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "BDX",
    name: "Becton Dickinson",
    marketCap: 71806,
    pe: 42.3,
    divYield: 1.8,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "BRK.B",
    name: "Berkshire Hathaway",
    marketCap: 0,
    pe: 0,
    divYield: 0,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "BBY",
    name: "Best Buy",
    marketCap: 18357,
    pe: 14.7,
    divYield: 4,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "TECH",
    name: "Bio-Techne",
    marketCap: 11687,
    pe: 77.4,
    divYield: 0.4,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "BIIB",
    name: "Biogen",
    marketCap: 20973,
    pe: 13,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "BLK",
    name: "BlackRock",
    marketCap: 166572,
    pe: 25.6,
    divYield: 2.1,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "BX",
    name: "Blackstone Inc.",
    marketCap: 216281,
    pe: 48.8,
    divYield: 1.9,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "XYZ",
    name: "Block, Inc.",
    marketCap: 0,
    pe: 0,
    divYield: 0,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "BK",
    name: "BNY Mellon",
    marketCap: 61670,
    pe: 14.8,
    divYield: 2.5,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "BA",
    name: "Boeing",
    marketCap: 132252,
    pe: 0,
    divYield: 0,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "BKNG",
    name: "Booking Holdings",
    marketCap: 158015,
    pe: 32.3,
    divYield: 0.7,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "BSX",
    name: "Boston Scientific",
    marketCap: 150861,
    pe: 84.6,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "BMY",
    name: "Bristol Myers Squibb",
    marketCap: 119946,
    pe: 0,
    divYield: 4.2,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "AVGO",
    name: "Broadcom",
    marketCap: 1037172,
    pe: 171.5,
    divYield: 1.2,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "BR",
    name: "Broadridge Financial Solutions",
    marketCap: 27845,
    pe: 41.1,
    divYield: 1.5,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "BRO",
    name: "Brown & Brown",
    marketCap: 29928,
    pe: 30.2,
    divYield: 0.6,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "BF.B",
    name: "Brown–Forman",
    marketCap: 0,
    pe: 0,
    divYield: 0,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "BLDR",
    name: "Builders FirstSource",
    marketCap: 19251,
    pe: 16.4,
    divYield: 0,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "BG",
    name: "Bunge Global",
    marketCap: 10630,
    pe: 9.6,
    divYield: 3.5,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "BXP",
    name: "BXP, Inc.",
    marketCap: 12905,
    pe: 31.8,
    divYield: 5.4,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "CHRW",
    name: "C.H. Robinson",
    marketCap: 11760,
    pe: 25.8,
    divYield: 2.3,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "CDNS",
    name: "Cadence Design Systems",
    marketCap: 81626,
    pe: 78.1,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "CZR",
    name: "Caesars Entertainment",
    marketCap: 7660,
    pe: 0,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "CPT",
    name: "Camden Property Trust",
    marketCap: 12131,
    pe: 35.9,
    divYield: 3.6,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "CPB",
    name: "Campbell's Company (The)",
    marketCap: 11558,
    pe: 21.2,
    divYield: 3.3,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "COF",
    name: "Capital One",
    marketCap: 77660,
    pe: 17.6,
    divYield: 1.2,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "CAH",
    name: "Cardinal Health",
    marketCap: 29872,
    pe: 23,
    divYield: 1.6,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "KMX",
    name: "CarMax",
    marketCap: 13171,
    pe: 29.1,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "CCL",
    name: "Carnival",
    marketCap: 37407,
    pe: 19.2,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "CARR",
    name: "Carrier Global",
    marketCap: 59190,
    pe: 38.7,
    divYield: 1.4,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "CAT",
    name: "Caterpillar Inc.",
    marketCap: 179332,
    pe: 16.8,
    divYield: 1.4,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "CBOE",
    name: "Cboe Global Markets",
    marketCap: 21390,
    pe: 27.9,
    divYield: 1.2,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "CBRE",
    name: "CBRE Group",
    marketCap: 44293,
    pe: 46.7,
    divYield: 0,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "CDW",
    name: "CDW Corporation",
    marketCap: 26538,
    pe: 24.3,
    divYield: 1.3,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "COR",
    name: "Cencora",
    marketCap: 49280,
    pe: 33.8,
    divYield: 0.9,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "CNC",
    name: "Centene Corporation",
    marketCap: 32327,
    pe: 11.1,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "CNP",
    name: "CenterPoint Energy",
    marketCap: 21227,
    pe: 21.7,
    divYield: 2.7,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "CF",
    name: "CF Industries",
    marketCap: 16046,
    pe: 14.6,
    divYield: 2.2,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "CRL",
    name: "Charles River Laboratories",
    marketCap: 8467,
    pe: 20.7,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "SCHW",
    name: "Charles Schwab Corporation",
    marketCap: 151424,
    pe: 27.7,
    divYield: 1.2,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "CHTR",
    name: "Charter Communications",
    marketCap: 49042,
    pe: 10.8,
    divYield: 0,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "CVX",
    name: "Chevron Corporation",
    marketCap: 278706,
    pe: 17.2,
    divYield: 4.2,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "CMG",
    name: "Chipotle Mexican Grill",
    marketCap: 79507,
    pe: 54,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "CB",
    name: "Chubb Limited",
    marketCap: 108943,
    pe: 12.1,
    divYield: 1.3,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "CHD",
    name: "Church & Dwight",
    marketCap: 25852,
    pe: 47.3,
    divYield: 1.1,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "CI",
    name: "Cigna",
    marketCap: 80551,
    pe: 24.3,
    divYield: 1.9,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "CINF",
    name: "Cincinnati Financial",
    marketCap: 21423,
    pe: 7,
    divYield: 2.3,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "CTAS",
    name: "Cintas",
    marketCap: 80939,
    pe: 48.4,
    divYield: 0.8,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "CSCO",
    name: "Cisco",
    marketCap: 241355,
    pe: 26,
    divYield: 2.7,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "C",
    name: "Citigroup",
    marketCap: 153659,
    pe: 13.8,
    divYield: 2.9,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "CFG",
    name: "Citizens Financial Group",
    marketCap: 20957,
    pe: 15.7,
    divYield: 3.5,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "CLX",
    name: "Clorox",
    marketCap: 19642,
    pe: 55.3,
    divYield: 3,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "CME",
    name: "CME Group",
    marketCap: 85233,
    pe: 24.9,
    divYield: 4.4,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "CMS",
    name: "CMS Energy",
    marketCap: 19720,
    pe: 18.9,
    divYield: 3.1,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "KO",
    name: "Coca-Cola Company (The)",
    marketCap: 275915,
    pe: 26.6,
    divYield: 3,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "CTSH",
    name: "Cognizant",
    marketCap: 40960,
    pe: 18.3,
    divYield: 1.5,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "COIN",
    name: "Coinbase",
    marketCap: 0,
    pe: 0,
    divYield: 0,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "CL",
    name: "Colgate-Palmolive",
    marketCap: 70835,
    pe: 24.9,
    divYield: 2.2,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "CMCSA",
    name: "Comcast",
    marketCap: 128484,
    pe: 8,
    divYield: 3.3,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "CAG",
    name: "Conagra Brands",
    marketCap: 12358,
    pe: 25.1,
    divYield: 5.1,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "COP",
    name: "ConocoPhillips",
    marketCap: 127843,
    pe: 11.7,
    divYield: 3.1,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "ED",
    name: "Consolidated Edison",
    marketCap: 32477,
    pe: 17.6,
    divYield: 3.6,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "STZ",
    name: "Constellation Brands",
    marketCap: 33317,
    pe: 49.3,
    divYield: 1.8,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "CEG",
    name: "Constellation Energy",
    marketCap: 96526,
    pe: 34,
    divYield: 0.5,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "COO",
    name: "Cooper Companies (The)",
    marketCap: 19270,
    pe: 49.3,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "CPRT",
    name: "Copart",
    marketCap: 55817,
    pe: 40.5,
    divYield: 0,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "GLW",
    name: "Corning Inc.",
    marketCap: 44539,
    pe: 89.8,
    divYield: 2.2,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "CPAY",
    name: "Corpay",
    marketCap: 26524,
    pe: 27.1,
    divYield: 0,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "CTVA",
    name: "Corteva",
    marketCap: 45464,
    pe: 68.7,
    divYield: 1,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "CSGP",
    name: "CoStar Group",
    marketCap: 31403,
    pe: 182.4,
    divYield: 0,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "COST",
    name: "Costco",
    marketCap: 434968,
    pe: 57.5,
    divYield: 0.5,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "CTRA",
    name: "Coterra",
    marketCap: 20414,
    pe: 16.8,
    divYield: 3,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "CRWD",
    name: "CrowdStrike",
    marketCap: 98049,
    pe: 765.5,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "CCI",
    name: "Crown Castle",
    marketCap: 38801,
    pe: 31.7,
    divYield: 7,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "CSX",
    name: "CSX Corporation",
    marketCap: 63387,
    pe: 18.4,
    divYield: 1.4,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "CMI",
    name: "Cummins",
    marketCap: 48871,
    pe: 23.3,
    divYield: 2,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "CVS",
    name: "CVS Health",
    marketCap: 71075,
    pe: 14.3,
    divYield: 4.7,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "DHR",
    name: "Danaher Corporation",
    marketCap: 160172,
    pe: 42.1,
    divYield: 0.5,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "DRI",
    name: "Darden Restaurants",
    marketCap: 22872,
    pe: 22.3,
    divYield: 3.5,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "DDOG",
    name: "Datadog",
    marketCap: 0,
    pe: 0,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "DVA",
    name: "DaVita",
    marketCap: 14453,
    pe: 19,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "DAY",
    name: "Dayforce",
    marketCap: 11156,
    pe: 208.1,
    divYield: 0,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "DECK",
    name: "Deckers Brands",
    marketCap: 33895,
    pe: 36.2,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "DE",
    name: "Deere & Company",
    marketCap: 129792,
    pe: 18.6,
    divYield: 1.5,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "DELL",
    name: "Dell Technologies",
    marketCap: 72282,
    pe: 18.3,
    divYield: 1.3,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "DAL",
    name: "Delta Air Lines",
    marketCap: 43408,
    pe: 12.6,
    divYield: 1,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "DVN",
    name: "Devon Energy",
    marketCap: 22400,
    pe: 6.3,
    divYield: 4.1,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "DXCM",
    name: "Dexcom",
    marketCap: 33915,
    pe: 52.6,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "FANG",
    name: "Diamondback Energy",
    marketCap: 47991,
    pe: 9.5,
    divYield: 4.9,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "DLR",
    name: "Digital Realty",
    marketCap: 55403,
    pe: 133.2,
    divYield: 3,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "DG",
    name: "Dollar General",
    marketCap: 15628,
    pe: 11.7,
    divYield: 3,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "DLTR",
    name: "Dollar Tree",
    marketCap: 15773,
    pe: 0,
    divYield: 0,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "D",
    name: "Dominion Energy",
    marketCap: 46696,
    pe: 20.5,
    divYield: 4.8,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "DPZ",
    name: "Domino's",
    marketCap: 15509,
    pe: 27.6,
    divYield: 1.3,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "DASH",
    name: "DoorDash",
    marketCap: 0,
    pe: 0,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "DOV",
    name: "Dover Corporation",
    marketCap: 27943,
    pe: 20.2,
    divYield: 1,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "DOW",
    name: "Dow Inc.",
    marketCap: 27476,
    pe: 24.9,
    divYield: 6.8,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "DHI",
    name: "D. R. Horton",
    marketCap: 45526,
    pe: 10,
    divYield: 1.1,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "DTE",
    name: "DTE Energy",
    marketCap: 24827,
    pe: 16.3,
    divYield: 3.7,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "DUK",
    name: "Duke Energy",
    marketCap: 86510,
    pe: 20.1,
    divYield: 3.7,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "DD",
    name: "DuPont",
    marketCap: 32099,
    pe: 60,
    divYield: 2,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "EMN",
    name: "Eastman Chemical Company",
    marketCap: 11551,
    pe: 13,
    divYield: 3.6,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "ETN",
    name: "Eaton Corporation",
    marketCap: 129009,
    pe: 34.8,
    divYield: 1.2,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "EBAY",
    name: "eBay Inc.",
    marketCap: 32342,
    pe: 17,
    divYield: 1.6,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "ECL",
    name: "Ecolab",
    marketCap: 70844,
    pe: 35.1,
    divYield: 1,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "EIX",
    name: "Edison International",
    marketCap: 20906,
    pe: 15.8,
    divYield: 6.1,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "EW",
    name: "Edwards Lifesciences",
    marketCap: 43185,
    pe: 28.3,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "EA",
    name: "Electronic Arts",
    marketCap: 32236,
    pe: 31.5,
    divYield: 0.6,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "ELV",
    name: "Elevance Health",
    marketCap: 91772,
    pe: 15.4,
    divYield: 1.7,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "EMR",
    name: "Emerson Electric",
    marketCap: 74011,
    pe: 46.1,
    divYield: 1.6,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "ENPH",
    name: "Enphase Energy",
    marketCap: 8414,
    pe: 135.4,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "ETR",
    name: "Entergy",
    marketCap: 34768,
    pe: 19.7,
    divYield: 3,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "EOG",
    name: "EOG Resources",
    marketCap: 70751,
    pe: 10.2,
    divYield: 3,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "EPAM",
    name: "EPAM Systems",
    marketCap: 14405,
    pe: 33,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "EQT",
    name: "EQT Corporation",
    marketCap: 30502,
    pe: 68.2,
    divYield: 1.2,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "EFX",
    name: "Equifax",
    marketCap: 34060,
    pe: 60.9,
    divYield: 0.6,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "EQIX",
    name: "Equinix",
    marketCap: 88157,
    pe: 82.5,
    divYield: 1.9,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "EQR",
    name: "Equity Residential",
    marketCap: 27623,
    pe: 29.8,
    divYield: 3.9,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "ERIE",
    name: "Erie Indemnity",
    marketCap: 21070,
    pe: 37.7,
    divYield: 1.4,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "ESS",
    name: "Essex Property Trust",
    marketCap: 18952,
    pe: 33.3,
    divYield: 3.5,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "EL",
    name: "Estée Lauder Companies (The)",
    marketCap: 29950,
    pe: 149,
    divYield: 1.6,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "EG",
    name: "Everest Group",
    marketCap: 14935,
    pe: 5.4,
    divYield: 2.3,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "EVRG",
    name: "Evergy",
    marketCap: 14776,
    pe: 17.3,
    divYield: 4.2,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "ES",
    name: "Eversource Energy",
    marketCap: 21134,
    pe: 0,
    divYield: 5.2,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "EXC",
    name: "Exelon",
    marketCap: 40193,
    pe: 16.5,
    divYield: 3.8,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "EXE",
    name: "Expand Energy",
    marketCap: 0,
    pe: 0,
    divYield: 0,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "EXPE",
    name: "Expedia Group",
    marketCap: 21941,
    pe: 22.2,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "EXPD",
    name: "Expeditors International",
    marketCap: 15898,
    pe: 22.1,
    divYield: 1.3,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "EXR",
    name: "Extra Space Storage",
    marketCap: 33966,
    pe: 41.2,
    divYield: 4.2,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "XOM",
    name: "ExxonMobil",
    marketCap: 481570,
    pe: 13.6,
    divYield: 3.6,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "FFIV",
    name: "F5, Inc.",
    marketCap: 17246,
    pe: 29.6,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "FDS",
    name: "FactSet",
    marketCap: 18042,
    pe: 34,
    divYield: 0.9,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "FICO",
    name: "Fair Isaac",
    marketCap: 45795,
    pe: 91.3,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "FAST",
    name: "Fastenal",
    marketCap: 41990,
    pe: 36.6,
    divYield: 2.1,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "FRT",
    name: "Federal Realty Investment Trust",
    marketCap: 9298,
    pe: 31.6,
    divYield: 4.1,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "FDX",
    name: "FedEx",
    marketCap: 63794,
    pe: 16.9,
    divYield: 2,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "FIS",
    name: "Fidelity National Information Services",
    marketCap: 43860,
    pe: 84,
    divYield: 1.8,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "FITB",
    name: "Fifth Third Bancorp",
    marketCap: 29681,
    pe: 14.1,
    divYield: 3.3,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "FSLR",
    name: "First Solar",
    marketCap: 17934,
    pe: 14.4,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "FE",
    name: "FirstEnergy",
    marketCap: 22937,
    pe: 25.7,
    divYield: 4.3,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "FI",
    name: "Fiserv",
    marketCap: 122909,
    pe: 41.7,
    divYield: 0,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "F",
    name: "Ford Motor Company",
    marketCap: 40061,
    pe: 11.5,
    divYield: 5.9,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "FTNT",
    name: "Fortinet",
    marketCap: 77320,
    pe: 50.7,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "FTV",
    name: "Fortive",
    marketCap: 28217,
    pe: 32.5,
    divYield: 0.4,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "FOXA",
    name: "Fox Corporation (Class A)",
    marketCap: 22750,
    pe: 12.5,
    divYield: 1.1,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "FOX",
    name: "Fox Corporation (Class B)",
    marketCap: 22786,
    pe: 11.9,
    divYield: 1.1,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "BEN",
    name: "Franklin Resources",
    marketCap: 11653,
    pe: 26.2,
    divYield: 6.4,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "FCX",
    name: "Freeport-McMoRan",
    marketCap: 52649,
    pe: 28.2,
    divYield: 1.5,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "GRMN",
    name: "Garmin",
    marketCap: 41449,
    pe: 27.4,
    divYield: 1.4,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "IT",
    name: "Gartner",
    marketCap: 41871,
    pe: 40.1,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "GE",
    name: "GE Aerospace",
    marketCap: 218571,
    pe: 33.5,
    divYield: 0.6,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "GEHC",
    name: "GE HealthCare",
    marketCap: 40342,
    pe: 24.2,
    divYield: 0.2,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "GEV",
    name: "GE Vernova",
    marketCap: 102786,
    pe: 66.7,
    divYield: 0.2,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "GEN",
    name: "Gen Digital",
    marketCap: 17188,
    pe: 27.7,
    divYield: 1.8,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "GNRC",
    name: "Generac",
    marketCap: 8885,
    pe: 31.1,
    divYield: 0,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "GD",
    name: "General Dynamics",
    marketCap: 69472,
    pe: 18.9,
    divYield: 2.2,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "GIS",
    name: "General Mills",
    marketCap: 33151,
    pe: 13.1,
    divYield: 3.6,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "GM",
    name: "General Motors",
    marketCap: 49253,
    pe: 7.8,
    divYield: 0.9,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "GPC",
    name: "Genuine Parts Company",
    marketCap: 16163,
    pe: 15,
    divYield: 3.4,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "GILD",
    name: "Gilead Sciences",
    marketCap: 121137,
    pe: 1080,
    divYield: 3.2,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "GPN",
    name: "Global Payments",
    marketCap: 28720,
    pe: 21.3,
    divYield: 0.9,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "GL",
    name: "Globe Life",
    marketCap: 10249,
    pe: 10.3,
    divYield: 0.8,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "GDDY",
    name: "GoDaddy",
    marketCap: 29978,
    pe: 17.1,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "GS",
    name: "Goldman Sachs",
    marketCap: 200457,
    pe: 15.9,
    divYield: 2.1,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "HAL",
    name: "Halliburton",
    marketCap: 22859,
    pe: 9.2,
    divYield: 2.3,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "HIG",
    name: "Hartford (The)",
    marketCap: 32337,
    pe: 10.8,
    divYield: 1.8,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "HAS",
    name: "Hasbro",
    marketCap: 8069,
    pe: 0,
    divYield: 4.7,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "HCA",
    name: "HCA Healthcare",
    marketCap: 83565,
    pe: 15,
    divYield: 0.8,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "DOC",
    name: "Healthpeak Properties",
    marketCap: 14450,
    pe: 42.2,
    divYield: 5.9,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "HSIC",
    name: "Henry Schein",
    marketCap: 9933,
    pe: 32.8,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "HSY",
    name: "Hershey Company (The)",
    marketCap: 30201,
    pe: 17.2,
    divYield: 3.6,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "HPE",
    name: "Hewlett Packard Enterprise",
    marketCap: 27872,
    pe: 11,
    divYield: 2.4,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "HLT",
    name: "Hilton Worldwide",
    marketCap: 62425,
    pe: 54.8,
    divYield: 0.2,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "HOLX",
    name: "Hologic",
    marketCap: 16284,
    pe: 21.7,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "HD",
    name: "Home Depot (The)",
    marketCap: 411749,
    pe: 28.2,
    divYield: 2.2,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "HON",
    name: "Honeywell",
    marketCap: 145695,
    pe: 25.8,
    divYield: 2,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "HRL",
    name: "Hormel Foods",
    marketCap: 16459,
    pe: 20.4,
    divYield: 3.7,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "HST",
    name: "Host Hotels & Resorts",
    marketCap: 11840,
    pe: 16.2,
    divYield: 4.8,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "HWM",
    name: "Howmet Aerospace",
    marketCap: 51425,
    pe: 48.7,
    divYield: 0.3,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "HPQ",
    name: "HP Inc.",
    marketCap: 30478,
    pe: 11.6,
    divYield: 2.8,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "HUBB",
    name: "Hubbell Incorporated",
    marketCap: 22703,
    pe: 30.4,
    divYield: 1.2,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "HUM",
    name: "Humana",
    marketCap: 35308,
    pe: 25.6,
    divYield: 1.2,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "HBAN",
    name: "Huntington Bancshares",
    marketCap: 25003,
    pe: 14.1,
    divYield: 3.7,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "HII",
    name: "Huntington Ingalls Industries",
    marketCap: 7719,
    pe: 11.2,
    divYield: 2.8,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "IBM",
    name: "IBM",
    marketCap: 238808,
    pe: 40.1,
    divYield: 2.9,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "IEX",
    name: "IDEX Corporation",
    marketCap: 16985,
    pe: 34.8,
    divYield: 1.2,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "IDXX",
    name: "Idexx Laboratories",
    marketCap: 34559,
    pe: 40.8,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "ITW",
    name: "Illinois Tool Works",
    marketCap: 76530,
    pe: 22.4,
    divYield: 2.3,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "INCY",
    name: "Incyte",
    marketCap: 14287,
    pe: 824,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "IR",
    name: "Ingersoll Rand",
    marketCap: 37887,
    pe: 46,
    divYield: 0.1,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "PODD",
    name: "Insulet Corporation",
    marketCap: 19527,
    pe: 47.3,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "INTC",
    name: "Intel",
    marketCap: 84132,
    pe: 0,
    divYield: 2.2,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "ICE",
    name: "Intercontinental Exchange",
    marketCap: 91771,
    pe: 38,
    divYield: 1.1,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "IFF",
    name: "International Flavors & Fragrances",
    marketCap: 22267,
    pe: 0,
    divYield: 1.8,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "IP",
    name: "International Paper",
    marketCap: 19326,
    pe: 35.4,
    divYield: 3.2,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "IPG",
    name: "Interpublic Group of Companies (The)",
    marketCap: 10680,
    pe: 13.5,
    divYield: 4.6,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "INTU",
    name: "Intuit",
    marketCap: 168373,
    pe: 58.5,
    divYield: 0.6,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "ISRG",
    name: "Intuitive Surgical",
    marketCap: 203692,
    pe: 88.8,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "IVZ",
    name: "Invesco",
    marketCap: 8615,
    pe: 16.3,
    divYield: 4.6,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "INVH",
    name: "Invitation Homes",
    marketCap: 19083,
    pe: 43.3,
    divYield: 3.7,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "IQV",
    name: "IQVIA",
    marketCap: 36547,
    pe: 26.5,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "IRM",
    name: "Iron Mountain",
    marketCap: 29807,
    pe: 282.1,
    divYield: 2.8,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "JBHT",
    name: "J.B. Hunt",
    marketCap: 17217,
    pe: 30.8,
    divYield: 0.9,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "JBL",
    name: "Jabil",
    marketCap: 17790,
    pe: 15.3,
    divYield: 0.2,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "JKHY",
    name: "Jack Henry & Associates",
    marketCap: 12701,
    pe: 31.8,
    divYield: 1.3,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "J",
    name: "Jacobs Solutions",
    marketCap: 17379,
    pe: 29.2,
    divYield: 0.8,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "JNJ",
    name: "Johnson & Johnson",
    marketCap: 368054,
    pe: 26.4,
    divYield: 3.4,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "JCI",
    name: "Johnson Controls",
    marketCap: 51491,
    pe: 37.5,
    divYield: 1.9,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "JPM",
    name: "JPMorgan Chase",
    marketCap: 747798,
    pe: 13.5,
    divYield: 2,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "K",
    name: "Kellanova",
    marketCap: 28172,
    pe: 27.3,
    divYield: 2.8,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "KVUE",
    name: "Kenvue",
    marketCap: 40818,
    pe: 38.7,
    divYield: 3.8,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "KDP",
    name: "Keurig Dr Pepper",
    marketCap: 43542,
    pe: 19.3,
    divYield: 2.8,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "KEY",
    name: "KeyCorp",
    marketCap: 19900,
    pe: 0,
    divYield: 4.5,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "KEYS",
    name: "Keysight Technologies",
    marketCap: 30838,
    pe: 50.8,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "KMB",
    name: "Kimberly-Clark",
    marketCap: 43124,
    pe: 17.2,
    divYield: 3.7,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "KIM",
    name: "Kimco Realty",
    marketCap: 15133,
    pe: 41.6,
    divYield: 4.4,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "KMI",
    name: "Kinder Morgan",
    marketCap: 61051,
    pe: 23.5,
    divYield: 3.7,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "KKR",
    name: "KKR & Co.",
    marketCap: 154172,
    pe: 51.6,
    divYield: 0.4,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "KLAC",
    name: "KLA Corporation",
    marketCap: 98747,
    pe: 31.1,
    divYield: 0.9,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "KHC",
    name: "Kraft Heinz",
    marketCap: 36082,
    pe: 26.9,
    divYield: 5.3,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "KR",
    name: "Kroger",
    marketCap: 44603,
    pe: 16.3,
    divYield: 2.1,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "LHX",
    name: "L3Harris",
    marketCap: 40212,
    pe: 26.9,
    divYield: 2.2,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "LH",
    name: "Labcorp",
    marketCap: 20893,
    pe: 47.3,
    divYield: 1.1,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "LRCX",
    name: "Lam Research",
    marketCap: 104146,
    pe: 24.6,
    divYield: 1.2,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "LW",
    name: "Lamb Weston",
    marketCap: 8550,
    pe: 23.6,
    divYield: 1.8,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "LVS",
    name: "Las Vegas Sands",
    marketCap: 33228,
    pe: 23.4,
    divYield: 1.8,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "LDOS",
    name: "Leidos",
    marketCap: 18951,
    pe: 16.2,
    divYield: 1.1,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "LEN",
    name: "Lennar",
    marketCap: 34667,
    pe: 9.2,
    divYield: 1.4,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "LII",
    name: "Lennox International",
    marketCap: 0,
    pe: 0,
    divYield: 0,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "LLY",
    name: "Lilly (Eli)",
    marketCap: 729417,
    pe: 87.2,
    divYield: 0.7,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "LIN",
    name: "Linde plc",
    marketCap: 212424,
    pe: 33.9,
    divYield: 1.3,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "LYV",
    name: "Live Nation Entertainment",
    marketCap: 33363,
    pe: 162.6,
    divYield: 0,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "LKQ",
    name: "LKQ Corporation",
    marketCap: 9720,
    pe: 13.8,
    divYield: 3.1,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "LMT",
    name: "Lockheed Martin",
    marketCap: 108972,
    pe: 20.8,
    divYield: 2.6,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "L",
    name: "Loews Corporation",
    marketCap: 18507,
    pe: 11.4,
    divYield: 0.3,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "LOW",
    name: "Lowe's",
    marketCap: 146832,
    pe: 21.7,
    divYield: 1.7,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "LULU",
    name: "Lululemon Athletica",
    marketCap: 50443,
    pe: 30,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "LYB",
    name: "LyondellBasell",
    marketCap: 24584,
    pe: 11.5,
    divYield: 7,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "MTB",
    name: "M&T Bank",
    marketCap: 33390,
    pe: 13.7,
    divYield: 2.7,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "MPC",
    name: "Marathon Petroleum",
    marketCap: 46830,
    pe: 11.3,
    divYield: 2.4,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "MKTX",
    name: "MarketAxess",
    marketCap: 8319,
    pe: 29.9,
    divYield: 1.4,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "MAR",
    name: "Marriott International",
    marketCap: 80753,
    pe: 30.5,
    divYield: 0.9,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "MMC",
    name: "Marsh McLennan",
    marketCap: 106515,
    pe: 26.5,
    divYield: 1.5,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "MLM",
    name: "Martin Marietta Materials",
    marketCap: 33256,
    pe: 16.9,
    divYield: 0.6,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "MAS",
    name: "Masco",
    marketCap: 17105,
    pe: 21.1,
    divYield: 1.4,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "MA",
    name: "Mastercard",
    marketCap: 517369,
    pe: 40.8,
    divYield: 0.6,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "MTCH",
    name: "Match Group",
    marketCap: 8964,
    pe: 16,
    divYield: 2.2,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "MKC",
    name: "McCormick & Company",
    marketCap: 20693,
    pe: 26.4,
    divYield: 2.5,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "MCD",
    name: "McDonald's",
    marketCap: 208049,
    pe: 25.5,
    divYield: 2.4,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "MCK",
    name: "McKesson Corporation",
    marketCap: 75498,
    pe: 30.7,
    divYield: 0.5,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "MDT",
    name: "Medtronic",
    marketCap: 116458,
    pe: 27.8,
    divYield: 3.2,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "MRK",
    name: "Merck & Co.",
    marketCap: 249979,
    pe: 20.7,
    divYield: 3.3,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "META",
    name: "Meta Platforms",
    marketCap: 1740621,
    pe: 28.8,
    divYield: 0.3,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "MET",
    name: "MetLife",
    marketCap: 59901,
    pe: 17.5,
    divYield: 2.5,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "MTD",
    name: "Mettler Toledo",
    marketCap: 28793,
    pe: 36.8,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "MGM",
    name: "MGM Resorts",
    marketCap: 10266,
    pe: 12.4,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "MCHP",
    name: "Microchip Technology",
    marketCap: 29160,
    pe: 37.7,
    divYield: 3.3,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "MU",
    name: "Micron Technology",
    marketCap: 103061,
    pe: 26.5,
    divYield: 0.4,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "MSFT",
    name: "Microsoft",
    marketCap: 3085548,
    pe: 33.4,
    divYield: 0.8,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "MAA",
    name: "Mid-America Apartment Communities",
    marketCap: 18303,
    pe: 34.4,
    divYield: 4,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "MRNA",
    name: "Moderna",
    marketCap: 15170,
    pe: 0,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "MHK",
    name: "Mohawk Industries",
    marketCap: 7720,
    pe: 13.8,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "MOH",
    name: "Molina Healthcare",
    marketCap: 17755,
    pe: 15.8,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "TAP",
    name: "Molson Coors Beverage Company",
    marketCap: 11287,
    pe: 12.3,
    divYield: 3.2,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "MDLZ",
    name: "Mondelez International",
    marketCap: 77544,
    pe: 20.6,
    divYield: 3.2,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "MPWR",
    name: "Monolithic Power Systems",
    marketCap: 31091,
    pe: 72,
    divYield: 0.8,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "MNST",
    name: "Monster Beverage",
    marketCap: 47371,
    pe: 31.2,
    divYield: 0,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "MCO",
    name: "Moody's Corporation",
    marketCap: 90514,
    pe: 45.7,
    divYield: 0.7,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "MS",
    name: "Morgan Stanley",
    marketCap: 222457,
    pe: 17.4,
    divYield: 2.8,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "MOS",
    name: "Mosaic Company (The)",
    marketCap: 8859,
    pe: 24.7,
    divYield: 3.1,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "MSI",
    name: "Motorola Solutions",
    marketCap: 78422,
    pe: 51.5,
    divYield: 0.9,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "MSCI",
    name: "MSCI Inc.",
    marketCap: 46770,
    pe: 42.4,
    divYield: 1,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "NDAQ",
    name: "Nasdaq, Inc.",
    marketCap: 47326,
    pe: 42.7,
    divYield: 1.2,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "NTAP",
    name: "NetApp",
    marketCap: 24824,
    pe: 22.5,
    divYield: 1.6,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "NFLX",
    name: "Netflix",
    marketCap: 417816,
    pe: 49,
    divYield: 0,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "NEM",
    name: "Newmont",
    marketCap: 49056,
    pe: 0,
    divYield: 2.3,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "NWSA",
    name: "News Corp (Class A)",
    marketCap: 16623,
    pe: 45.4,
    divYield: 0.7,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "NWS",
    name: "News Corp (Class B)",
    marketCap: 16626,
    pe: 51,
    divYield: 0.6,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "NEE",
    name: "NextEra Energy",
    marketCap: 147156,
    pe: 21.2,
    divYield: 3,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "NKE",
    name: "Nike, Inc.",
    marketCap: 115860,
    pe: 24.2,
    divYield: 2.1,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "NI",
    name: "NiSource",
    marketCap: 17411,
    pe: 22.7,
    divYield: 3,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "NDSN",
    name: "Nordson Corporation",
    marketCap: 12572,
    pe: 27.1,
    divYield: 1.3,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "NSC",
    name: "Norfolk Southern",
    marketCap: 57780,
    pe: 22.1,
    divYield: 2.1,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "NTRS",
    name: "Northern Trust",
    marketCap: 22005,
    pe: 11.5,
    divYield: 2.7,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "NOC",
    name: "Northrop Grumman",
    marketCap: 70631,
    pe: 17.2,
    divYield: 1.7,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "NCLH",
    name: "Norwegian Cruise Line Holdings",
    marketCap: 12466,
    pe: 24.9,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "NRG",
    name: "NRG Energy",
    marketCap: 20751,
    pe: 25.4,
    divYield: 1.7,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "NUE",
    name: "Nucor",
    marketCap: 30157,
    pe: 15.2,
    divYield: 1.8,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "NVDA",
    name: "Nvidia",
    marketCap: 3052684,
    pe: 49.2,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "NVR",
    name: "NVR, Inc.",
    marketCap: 24920,
    pe: 15.8,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "NXPI",
    name: "NXP Semiconductors",
    marketCap: 53004,
    pe: 19.9,
    divYield: 1.9,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "ORLY",
    name: "O’Reilly Automotive",
    marketCap: 74728,
    pe: 32.1,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "OXY",
    name: "Occidental Petroleum",
    marketCap: 43774,
    pe: 12.8,
    divYield: 1.8,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "ODFL",
    name: "Old Dominion",
    marketCap: 39627,
    pe: 32.4,
    divYield: 0.6,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "OMC",
    name: "Omnicom Group",
    marketCap: 17053,
    pe: 11.9,
    divYield: 3.2,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "ON",
    name: "ON Semiconductor",
    marketCap: 22286,
    pe: 13,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "OKE",
    name: "Oneok",
    marketCap: 56646,
    pe: 20.6,
    divYield: 4.1,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "ORCL",
    name: "Oracle Corporation",
    marketCap: 475651,
    pe: 41.6,
    divYield: 0.8,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "OTIS",
    name: "Otis Worldwide",
    marketCap: 38117,
    pe: 23.4,
    divYield: 1.6,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "PCAR",
    name: "Paccar",
    marketCap: 58145,
    pe: 14,
    divYield: 1.2,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "PKG",
    name: "Packaging Corporation of America",
    marketCap: 19098,
    pe: 23.8,
    divYield: 2.1,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "PLTR",
    name: "Palantir Technologies",
    marketCap: 187914,
    pe: 412.4,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "PANW",
    name: "Palo Alto Networks",
    marketCap: 121016,
    pe: 47.8,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "PSKY",
    name: "Paramount Skydance Corporation",
    marketCap: 0,
    pe: 0,
    divYield: 0,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "PH",
    name: "Parker Hannifin",
    marketCap: 91011,
    pe: 29.2,
    divYield: 1,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "PAYX",
    name: "Paychex",
    marketCap: 53171,
    pe: 31.1,
    divYield: 2.9,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "PAYC",
    name: "Paycom",
    marketCap: 11968,
    pe: 25,
    divYield: 0.7,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "PYPL",
    name: "PayPal",
    marketCap: 89797,
    pe: 21.4,
    divYield: 0,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "PNR",
    name: "Pentair",
    marketCap: 17131,
    pe: 25.9,
    divYield: 1,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "PEP",
    name: "PepsiCo",
    marketCap: 208406,
    pe: 22.4,
    divYield: 3.6,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "PFE",
    name: "Pfizer",
    marketCap: 150289,
    pe: 35.4,
    divYield: 6.4,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "PCG",
    name: "PG&E Corporation",
    marketCap: 34328,
    pe: 12.2,
    divYield: 0.6,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "PM",
    name: "Philip Morris International",
    marketCap: 202439,
    pe: 20.7,
    divYield: 4.1,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "PSX",
    name: "Phillips 66",
    marketCap: 48679,
    pe: 15.1,
    divYield: 3.8,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "PNW",
    name: "Pinnacle West Capital",
    marketCap: 9887,
    pe: 16.3,
    divYield: 4.1,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "PNC",
    name: "PNC Financial Services",
    marketCap: 79564,
    pe: 14.6,
    divYield: 3.2,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "POOL",
    name: "Pool Corporation",
    marketCap: 13101,
    pe: 29.6,
    divYield: 1.4,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "PPG",
    name: "PPG Industries",
    marketCap: 26768,
    pe: 18.3,
    divYield: 2.2,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "PPL",
    name: "PPL Corporation",
    marketCap: 24796,
    pe: 30.3,
    divYield: 3.1,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "PFG",
    name: "Principal Financial Group",
    marketCap: 18858,
    pe: 0,
    divYield: 3.5,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "PG",
    name: "Procter & Gamble",
    marketCap: 389222,
    pe: 26.4,
    divYield: 2.5,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "PGR",
    name: "Progressive Corporation",
    marketCap: 144367,
    pe: 17.1,
    divYield: 2,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "PLD",
    name: "Prologis",
    marketCap: 110446,
    pe: 36,
    divYield: 3.3,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "PRU",
    name: "Prudential Financial",
    marketCap: 42982,
    pe: 10.8,
    divYield: 4.3,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "PEG",
    name: "Public Service Enterprise Group",
    marketCap: 41622,
    pe: 20.5,
    divYield: 2.9,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "PTC",
    name: "PTC Inc.",
    marketCap: 23286,
    pe: 62.2,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "PSA",
    name: "Public Storage",
    marketCap: 52289,
    pe: 31,
    divYield: 4,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "PHM",
    name: "PulteGroup",
    marketCap: 23334,
    pe: 7.7,
    divYield: 0.8,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "PWR",
    name: "Quanta Services",
    marketCap: 45407,
    pe: 56.9,
    divYield: 0.1,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "QCOM",
    name: "Qualcomm",
    marketCap: 191155,
    pe: 19.2,
    divYield: 2,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "DGX",
    name: "Quest Diagnostics",
    marketCap: 18041,
    pe: 21.2,
    divYield: 1.9,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "RL",
    name: "Ralph Lauren Corporation",
    marketCap: 15506,
    pe: 23.8,
    divYield: 1.3,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "RJF",
    name: "Raymond James Financial",
    marketCap: 34471,
    pe: 16.5,
    divYield: 1.2,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "RTX",
    name: "RTX Corporation",
    marketCap: 171675,
    pe: 36.3,
    divYield: 2,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "O",
    name: "Realty Income",
    marketCap: 47822,
    pe: 52,
    divYield: 5.8,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "REG",
    name: "Regency Centers",
    marketCap: 13118,
    pe: 33.9,
    divYield: 3.9,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "REGN",
    name: "Regeneron Pharmaceuticals",
    marketCap: 73954,
    pe: 16.6,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "RF",
    name: "Regions Financial Corporation",
    marketCap: 22394,
    pe: 12.8,
    divYield: 4.1,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "RSG",
    name: "Republic Services",
    marketCap: 67913,
    pe: 34.7,
    divYield: 1.1,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "RMD",
    name: "ResMed",
    marketCap: 34670,
    pe: 27.9,
    divYield: 0.8,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "RVTY",
    name: "Revvity",
    marketCap: 15350,
    pe: 60.3,
    divYield: 0.2,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "ROK",
    name: "Rockwell Automation",
    marketCap: 31472,
    pe: 33.6,
    divYield: 1.9,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "ROL",
    name: "Rollins, Inc.",
    marketCap: 24080,
    pe: 51,
    divYield: 1.3,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "ROP",
    name: "Roper Technologies",
    marketCap: 61726,
    pe: 40.2,
    divYield: 0.6,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "ROST",
    name: "Ross Stores",
    marketCap: 49674,
    pe: 23.7,
    divYield: 1,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "RCL",
    name: "Royal Caribbean Group",
    marketCap: 71689,
    pe: 24.3,
    divYield: 0.9,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "SPGI",
    name: "S&P Global",
    marketCap: 161794,
    pe: 46.1,
    divYield: 0.7,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "CRM",
    name: "Salesforce",
    marketCap: 328796,
    pe: 56.5,
    divYield: 0.5,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "SBAC",
    name: "SBA Communications",
    marketCap: 21242,
    pe: 31.2,
    divYield: 2,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "SLB",
    name: "Schlumberger",
    marketCap: 57463,
    pe: 13.2,
    divYield: 2.7,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "STX",
    name: "Seagate Technology",
    marketCap: 20807,
    pe: 17.8,
    divYield: 2.8,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "SRE",
    name: "Sempra",
    marketCap: 52528,
    pe: 18.3,
    divYield: 3,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "NOW",
    name: "ServiceNow",
    marketCap: 210282,
    pe: 147.8,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "SHW",
    name: "Sherwin-Williams",
    marketCap: 90204,
    pe: 33.9,
    divYield: 0.8,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "SPG",
    name: "Simon Property Group",
    marketCap: 65280,
    pe: 23.1,
    divYield: 4.8,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "SWKS",
    name: "Skyworks Solutions",
    marketCap: 14267,
    pe: 24.1,
    divYield: 3.4,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "SJM",
    name: "J.M. Smucker Company (The)",
    marketCap: 11375,
    pe: 21.6,
    divYield: 3.8,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "SW",
    name: "Smurfit Westrock",
    marketCap: 27615,
    pe: 73.7,
    divYield: 4.3,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "SNA",
    name: "Snap-on",
    marketCap: 18642,
    pe: 18.3,
    divYield: 2.4,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "SOLV",
    name: "Solventum",
    marketCap: 12794,
    pe: 194.9,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "SO",
    name: "Southern Company",
    marketCap: 91982,
    pe: 19.6,
    divYield: 3.4,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "LUV",
    name: "Southwest Airlines",
    marketCap: 18418,
    pe: 40.4,
    divYield: 2.3,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "SWK",
    name: "Stanley Black & Decker",
    marketCap: 13577,
    pe: 0,
    divYield: 3.7,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "SBUX",
    name: "Starbucks",
    marketCap: 123817,
    pe: 35.2,
    divYield: 2.4,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "STT",
    name: "State Street Corporation",
    marketCap: 29344,
    pe: 12.4,
    divYield: 3,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "STLD",
    name: "Steel Dynamics",
    marketCap: 19900,
    pe: 13.3,
    divYield: 1.5,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "STE",
    name: "Steris",
    marketCap: 21780,
    pe: 37.1,
    divYield: 1,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "SYK",
    name: "Stryker Corporation",
    marketCap: 149166,
    pe: 50.4,
    divYield: 0.9,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "SMCI",
    name: "Supermicro",
    marketCap: 16700,
    pe: 14.2,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "SYF",
    name: "Synchrony Financial",
    marketCap: 26785,
    pe: 8.1,
    divYield: 1.5,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "SNPS",
    name: "Synopsys",
    marketCap: 81228,
    pe: 56.7,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "SYY",
    name: "Sysco",
    marketCap: 35675,
    pe: 18.7,
    divYield: 2.7,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "TMUS",
    name: "T-Mobile US",
    marketCap: 266653,
    pe: 26.6,
    divYield: 1.6,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "TROW",
    name: "T. Rowe Price",
    marketCap: 25975,
    pe: 12.8,
    divYield: 4.3,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "TTWO",
    name: "Take-Two Interactive",
    marketCap: 32581,
    pe: 0,
    divYield: 0,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "TPR",
    name: "Tapestry, Inc.",
    marketCap: 16998,
    pe: 21.1,
    divYield: 1.8,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "TRGP",
    name: "Targa Resources",
    marketCap: 42915,
    pe: 35.7,
    divYield: 1.5,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "TGT",
    name: "Target Corporation",
    marketCap: 63192,
    pe: 14.6,
    divYield: 2.9,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "TEL",
    name: "TE Connectivity",
    marketCap: 44147,
    pe: 23.3,
    divYield: 1.8,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "TDY",
    name: "Teledyne Technologies",
    marketCap: 23829,
    pe: 29.7,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "TER",
    name: "Teradyne",
    marketCap: 18858,
    pe: 35,
    divYield: 0.4,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "TSLA",
    name: "Tesla, Inc.",
    marketCap: 1301404,
    pe: 196.4,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "TXN",
    name: "Texas Instruments",
    marketCap: 168404,
    pe: 35.4,
    divYield: 2.7,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "TPL",
    name: "Texas Pacific Land Corporation",
    marketCap: 0,
    pe: 0,
    divYield: 0,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "TXT",
    name: "Textron",
    marketCap: 14194,
    pe: 17.7,
    divYield: 0.1,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "TMO",
    name: "Thermo Fisher Scientific",
    marketCap: 228639,
    pe: 36.2,
    divYield: 0.3,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "TJX",
    name: "TJX Companies",
    marketCap: 140284,
    pe: 29.4,
    divYield: 1.3,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "TKO",
    name: "TKO Group Holdings",
    marketCap: 0,
    pe: 0,
    divYield: 0,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "TTD",
    name: "Trade Desk (The)",
    marketCap: 0,
    pe: 0,
    divYield: 0,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "TSCO",
    name: "Tractor Supply",
    marketCap: 29039,
    pe: 26.6,
    divYield: 1.5,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "TT",
    name: "Trane Technologies",
    marketCap: 82431,
    pe: 32.2,
    divYield: 0.9,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "TDG",
    name: "TransDigm Group",
    marketCap: 75841,
    pe: 52.7,
    divYield: 0,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "TRV",
    name: "Travelers Companies (The)",
    marketCap: 55558,
    pe: 11.4,
    divYield: 1.8,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "TRMB",
    name: "Trimble Inc.",
    marketCap: 18425,
    pe: 12.5,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "TFC",
    name: "Truist Financial",
    marketCap: 63191,
    pe: 0,
    divYield: 4.6,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "TYL",
    name: "Tyler Technologies",
    marketCap: 25749,
    pe: 110.4,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "TSN",
    name: "Tyson Foods",
    marketCap: 20120,
    pe: 25.1,
    divYield: 3.5,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "USB",
    name: "U.S. Bancorp",
    marketCap: 74537,
    pe: 12.6,
    divYield: 3.9,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "UBER",
    name: "Uber",
    marketCap: 140767,
    pe: 32.9,
    divYield: 0,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "UDR",
    name: "UDR, Inc.",
    marketCap: 15680,
    pe: 109.8,
    divYield: 4.1,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "ULTA",
    name: "Ulta Beauty",
    marketCap: 19112,
    pe: 16.5,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "UNP",
    name: "Union Pacific Corporation",
    marketCap: 150224,
    pe: 22.3,
    divYield: 2.3,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "UAL",
    name: "United Airlines Holdings",
    marketCap: 34808,
    pe: 11.2,
    divYield: 0,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "UPS",
    name: "United Parcel Service",
    marketCap: 97480,
    pe: 16.9,
    divYield: 4.9,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "URI",
    name: "United Rentals",
    marketCap: 49507,
    pe: 19.6,
    divYield: 0.9,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "UNH",
    name: "UnitedHealth Group",
    marketCap: 502079,
    pe: 35.2,
    divYield: 1.6,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "UHS",
    name: "Universal Health Services",
    marketCap: 12438,
    pe: 12.6,
    divYield: 0.4,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "VLO",
    name: "Valero Energy",
    marketCap: 42106,
    pe: 15.5,
    divYield: 3.2,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "VTR",
    name: "Ventas",
    marketCap: 25347,
    pe: 0,
    divYield: 3,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "VLTO",
    name: "Veralto",
    marketCap: 25569,
    pe: 31.9,
    divYield: 0.4,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "VRSN",
    name: "Verisign",
    marketCap: 20661,
    pe: 25.1,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "VRSK",
    name: "Verisk Analytics",
    marketCap: 40590,
    pe: 44.4,
    divYield: 0.5,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "VZ",
    name: "Verizon",
    marketCap: 165817,
    pe: 9.5,
    divYield: 6.9,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "VRTX",
    name: "Vertex Pharmaceuticals",
    marketCap: 118896,
    pe: 0,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "VTRS",
    name: "Viatris",
    marketCap: 13464,
    pe: 0,
    divYield: 4.2,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "VICI",
    name: "Vici Properties",
    marketCap: 31383,
    pe: 11,
    divYield: 5.8,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "V",
    name: "Visa Inc.",
    marketCap: 662323,
    pe: 34.6,
    divYield: 0.7,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "VST",
    name: "Vistra Corp.",
    marketCap: 57168,
    pe: 31.6,
    divYield: 0.5,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "VMC",
    name: "Vulcan Materials Company",
    marketCap: 36205,
    pe: 42.8,
    divYield: 0.7,
    sector: "Materials",
    index: "SP500"
  },
  {
    ticker: "WRB",
    name: "W. R. Berkley Corporation",
    marketCap: 22291,
    pe: 13.5,
    divYield: 0.6,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "GWW",
    name: "W. W. Grainger",
    marketCap: 51752,
    pe: 28.8,
    divYield: 0.7,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "WAB",
    name: "Wabtec",
    marketCap: 35739,
    pe: 34.7,
    divYield: 0.4,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "WBA",
    name: "Walgreens Boots Alliance",
    marketCap: 8883,
    pe: 0,
    divYield: 10.9,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "WMT",
    name: "Walmart",
    marketCap: 792494,
    pe: 40.9,
    divYield: 1,
    sector: "Consumer Staples",
    index: "SP500"
  },
  {
    ticker: "DIS",
    name: "Walt Disney Company (The)",
    marketCap: 205134,
    pe: 41.7,
    divYield: 0.8,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "WBD",
    name: "Warner Bros. Discovery",
    marketCap: 26053,
    pe: 0,
    divYield: 0,
    sector: "Communication Services",
    index: "SP500"
  },
  {
    ticker: "WM",
    name: "Waste Management",
    marketCap: 88405,
    pe: 32.3,
    divYield: 1.4,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "WAT",
    name: "Waters Corporation",
    marketCap: 24670,
    pe: 39.7,
    divYield: 0,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "WEC",
    name: "WEC Energy Group",
    marketCap: 31401,
    pe: 24.3,
    divYield: 3.6,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "WFC",
    name: "Wells Fargo",
    marketCap: 259235,
    pe: 14.7,
    divYield: 2.3,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "WELL",
    name: "Welltower",
    marketCap: 84985,
    pe: 87.5,
    divYield: 2,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "WST",
    name: "West Pharmaceutical Services",
    marketCap: 24736,
    pe: 50.7,
    divYield: 0.2,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "WDC",
    name: "Western Digital",
    marketCap: 22516,
    pe: 18.8,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "WY",
    name: "Weyerhaeuser",
    marketCap: 22248,
    pe: 41.9,
    divYield: 2.6,
    sector: "Real Estate",
    index: "SP500"
  },
  {
    ticker: "WSM",
    name: "Williams-Sonoma, Inc.",
    marketCap: 0,
    pe: 0,
    divYield: 0,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "WMB",
    name: "Williams Companies",
    marketCap: 67570,
    pe: 23.5,
    divYield: 3.5,
    sector: "Energy",
    index: "SP500"
  },
  {
    ticker: "WTW",
    name: "Willis Towers Watson",
    marketCap: 33195,
    pe: 0,
    divYield: 1.1,
    sector: "Financials",
    index: "SP500"
  },
  {
    ticker: "WDAY",
    name: "Workday, Inc.",
    marketCap: 0,
    pe: 0,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "WYNN",
    name: "Wynn Resorts",
    marketCap: 9537,
    pe: 10.4,
    divYield: 1.1,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "XEL",
    name: "Xcel Energy",
    marketCap: 38589,
    pe: 19.9,
    divYield: 3.3,
    sector: "Utilities",
    index: "SP500"
  },
  {
    ticker: "XYL",
    name: "Xylem Inc.",
    marketCap: 30135,
    pe: 35.6,
    divYield: 1.2,
    sector: "Industrials",
    index: "SP500"
  },
  {
    ticker: "YUM",
    name: "Yum! Brands",
    marketCap: 36419,
    pe: 24.4,
    divYield: 2,
    sector: "Consumer Discretionary",
    index: "SP500"
  },
  {
    ticker: "ZBRA",
    name: "Zebra Technologies",
    marketCap: 20216,
    pe: 53.4,
    divYield: 0,
    sector: "Information Technology",
    index: "SP500"
  },
  {
    ticker: "ZBH",
    name: "Zimmer Biomet",
    marketCap: 21795,
    pe: 20.9,
    divYield: 0.9,
    sector: "Health Care",
    index: "SP500"
  },
  {
    ticker: "ZTS",
    name: "Zoetis",
    marketCap: 77104,
    pe: 32.1,
    divYield: 1.2,
    sector: "Health Care",
    index: "SP500"
  }
];
